/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SecuriteRouteImport } from './routes/securite'
import { Route as QrRouteImport } from './routes/qr'
import { Route as MenuRouteImport } from './routes/menu'
import { Route as MentionsLegalesRouteImport } from './routes/mentions-legales'
import { Route as ConfidentialiteRouteImport } from './routes/confidentialite'
import { Route as CommandeRouteImport } from './routes/commande'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BackLoginRouteImport } from './routes/back/login'
import { Route as BackInitRouteImport } from './routes/back/init'
import { Route as BackCuisineRouteImport } from './routes/back/cuisine'
import { Route as BackAdminRouteImport } from './routes/back/admin'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SecuriteRoute = SecuriteRouteImport.update({
  id: '/securite',
  path: '/securite',
  getParentRoute: () => rootRouteImport,
} as any)
const QrRoute = QrRouteImport.update({
  id: '/qr',
  path: '/qr',
  getParentRoute: () => rootRouteImport,
} as any)
const MenuRoute = MenuRouteImport.update({
  id: '/menu',
  path: '/menu',
  getParentRoute: () => rootRouteImport,
} as any)
const MentionsLegalesRoute = MentionsLegalesRouteImport.update({
  id: '/mentions-legales',
  path: '/mentions-legales',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfidentialiteRoute = ConfidentialiteRouteImport.update({
  id: '/confidentialite',
  path: '/confidentialite',
  getParentRoute: () => rootRouteImport,
} as any)
const CommandeRoute = CommandeRouteImport.update({
  id: '/commande',
  path: '/commande',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BackLoginRoute = BackLoginRouteImport.update({
  id: '/back/login',
  path: '/back/login',
  getParentRoute: () => rootRouteImport,
} as any)
const BackInitRoute = BackInitRouteImport.update({
  id: '/back/init',
  path: '/back/init',
  getParentRoute: () => rootRouteImport,
} as any)
const BackCuisineRoute = BackCuisineRouteImport.update({
  id: '/back/cuisine',
  path: '/back/cuisine',
  getParentRoute: () => rootRouteImport,
} as any)
const BackAdminRoute = BackAdminRouteImport.update({
  id: '/back/admin',
  path: '/back/admin',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/commande': typeof CommandeRoute
  '/confidentialite': typeof ConfidentialiteRoute
  '/mentions-legales': typeof MentionsLegalesRoute
  '/menu': typeof MenuRoute
  '/qr': typeof QrRoute
  '/securite': typeof SecuriteRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/back/admin': typeof BackAdminRoute
  '/back/cuisine': typeof BackCuisineRoute
  '/back/init': typeof BackInitRoute
  '/back/login': typeof BackLoginRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/commande': typeof CommandeRoute
  '/confidentialite': typeof ConfidentialiteRoute
  '/mentions-legales': typeof MentionsLegalesRoute
  '/menu': typeof MenuRoute
  '/qr': typeof QrRoute
  '/securite': typeof SecuriteRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/back/admin': typeof BackAdminRoute
  '/back/cuisine': typeof BackCuisineRoute
  '/back/init': typeof BackInitRoute
  '/back/login': typeof BackLoginRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/commande': typeof CommandeRoute
  '/confidentialite': typeof ConfidentialiteRoute
  '/mentions-legales': typeof MentionsLegalesRoute
  '/menu': typeof MenuRoute
  '/qr': typeof QrRoute
  '/securite': typeof SecuriteRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/back/admin': typeof BackAdminRoute
  '/back/cuisine': typeof BackCuisineRoute
  '/back/init': typeof BackInitRoute
  '/back/login': typeof BackLoginRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/commande'
    | '/confidentialite'
    | '/mentions-legales'
    | '/menu'
    | '/qr'
    | '/securite'
    | '/sitemap.xml'
    | '/back/admin'
    | '/back/cuisine'
    | '/back/init'
    | '/back/login'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/commande'
    | '/confidentialite'
    | '/mentions-legales'
    | '/menu'
    | '/qr'
    | '/securite'
    | '/sitemap.xml'
    | '/back/admin'
    | '/back/cuisine'
    | '/back/init'
    | '/back/login'
  id:
    | '__root__'
    | '/'
    | '/commande'
    | '/confidentialite'
    | '/mentions-legales'
    | '/menu'
    | '/qr'
    | '/securite'
    | '/sitemap.xml'
    | '/back/admin'
    | '/back/cuisine'
    | '/back/init'
    | '/back/login'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CommandeRoute: typeof CommandeRoute
  ConfidentialiteRoute: typeof ConfidentialiteRoute
  MentionsLegalesRoute: typeof MentionsLegalesRoute
  MenuRoute: typeof MenuRoute
  QrRoute: typeof QrRoute
  SecuriteRoute: typeof SecuriteRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  BackAdminRoute: typeof BackAdminRoute
  BackCuisineRoute: typeof BackCuisineRoute
  BackInitRoute: typeof BackInitRoute
  BackLoginRoute: typeof BackLoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/securite': {
      id: '/securite'
      path: '/securite'
      fullPath: '/securite'
      preLoaderRoute: typeof SecuriteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/qr': {
      id: '/qr'
      path: '/qr'
      fullPath: '/qr'
      preLoaderRoute: typeof QrRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/menu': {
      id: '/menu'
      path: '/menu'
      fullPath: '/menu'
      preLoaderRoute: typeof MenuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mentions-legales': {
      id: '/mentions-legales'
      path: '/mentions-legales'
      fullPath: '/mentions-legales'
      preLoaderRoute: typeof MentionsLegalesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/confidentialite': {
      id: '/confidentialite'
      path: '/confidentialite'
      fullPath: '/confidentialite'
      preLoaderRoute: typeof ConfidentialiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/commande': {
      id: '/commande'
      path: '/commande'
      fullPath: '/commande'
      preLoaderRoute: typeof CommandeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/back/login': {
      id: '/back/login'
      path: '/back/login'
      fullPath: '/back/login'
      preLoaderRoute: typeof BackLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/back/init': {
      id: '/back/init'
      path: '/back/init'
      fullPath: '/back/init'
      preLoaderRoute: typeof BackInitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/back/cuisine': {
      id: '/back/cuisine'
      path: '/back/cuisine'
      fullPath: '/back/cuisine'
      preLoaderRoute: typeof BackCuisineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/back/admin': {
      id: '/back/admin'
      path: '/back/admin'
      fullPath: '/back/admin'
      preLoaderRoute: typeof BackAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CommandeRoute: CommandeRoute,
  ConfidentialiteRoute: ConfidentialiteRoute,
  MentionsLegalesRoute: MentionsLegalesRoute,
  MenuRoute: MenuRoute,
  QrRoute: QrRoute,
  SecuriteRoute: SecuriteRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  BackAdminRoute: BackAdminRoute,
  BackCuisineRoute: BackCuisineRoute,
  BackInitRoute: BackInitRoute,
  BackLoginRoute: BackLoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
