name = "etat-dame-site"
compatibility_date = "2026-06-30"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".output/public"

[[d1_databases]]
binding = "DB"
database_name = "etat-dame-db"
database_id = "163c62bd-0cfd-4382-aadd-d6d54f42ff1d"
migrations_dir = "drizzle"
